//Nome: Murillo Tadeu Amadeu -  RA: 02564246
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetofinal;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author muril
 */
public class CadastroCarro extends javax.swing.JFrame {
     static CadastroCarro cadCarroUnic;
    //metodo singleton
    public static CadastroCarro getCadCarroUnic(){
        if(cadCarroUnic == null){
            cadCarroUnic = new CadastroCarro();
        }
        return cadCarroUnic;
        
    }
    /**
     * Creates new form CadastroCarro
     */
    private CadastroCarro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cxQtdePassageiro = new javax.swing.JTextField();
        lQtdeViagemot = new javax.swing.JLabel();
        cxTipoCorrida = new javax.swing.JTextField();
        cxDistancia = new javax.swing.JTextField();
        lRuaMot = new javax.swing.JLabel();
        lPaisMot = new javax.swing.JLabel();
        cxPlaca = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        lNomeMot = new javax.swing.JLabel();
        cxCor = new javax.swing.JTextField();
        lCpfMot = new javax.swing.JLabel();
        cxTarifa = new javax.swing.JTextField();
        lIdadeMot = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btConsulta = new javax.swing.JButton();
        btAltera = new javax.swing.JButton();
        btDeleta = new javax.swing.JButton();
        btPessoa = new javax.swing.JButton();
        btVeic = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Carro");

        lQtdeViagemot.setText("Quantidade de Passageiros:");

        lRuaMot.setText("Tipo de corrida:");

        lPaisMot.setText("Distância:");

        btCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        lNomeMot.setText("Placa:");

        lCpfMot.setText("Cor:");

        lIdadeMot.setText("Tarifa unitária:");

        btSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btLimpar.setText("Limpar Formulário");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btConsulta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btConsulta.setText("Consultar");
        btConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaActionPerformed(evt);
            }
        });

        btAltera.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAltera.setText("Alterar");
        btAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlteraActionPerformed(evt);
            }
        });

        btDeleta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btDeleta.setText("Deletar");
        btDeleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletaActionPerformed(evt);
            }
        });

        btPessoa.setText("Tabela Cadastro Pessoas...");
        btPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPessoaActionPerformed(evt);
            }
        });

        btVeic.setText("Tabela Cadastro veiculos...");
        btVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVeicActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Para Pesquisar digite uma placa válida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btPessoa)
                                .addGap(18, 18, 18)
                                .addComponent(btVeic)
                                .addGap(28, 28, 28)
                                .addComponent(btLimpar)
                                .addGap(52, 52, 52)
                                .addComponent(btSair))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btConsulta)
                                .addGap(18, 18, 18)
                                .addComponent(btAltera)
                                .addGap(18, 18, 18)
                                .addComponent(btDeleta)
                                .addGap(40, 40, 40)))
                        .addGap(0, 18, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lIdadeMot)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btCadastrar)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lQtdeViagemot, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cxQtdePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lNomeMot, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lCpfMot, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cxCor))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(cxTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lRuaMot)
                                .addComponent(lPaisMot))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cxTipoCorrida, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(cxDistancia))))
                    .addContainerGap(68, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(130, 130, 130)
                .addComponent(lIdadeMot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsulta)
                    .addComponent(btAltera)
                    .addComponent(btDeleta))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btLimpar)
                    .addComponent(btPessoa)
                    .addComponent(btVeic))
                .addGap(17, 17, 17))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lNomeMot)
                        .addComponent(cxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lRuaMot)
                        .addComponent(cxTipoCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lCpfMot)
                        .addComponent(cxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lPaisMot)
                        .addComponent(cxDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(39, 39, 39)
                    .addComponent(cxTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lQtdeViagemot)
                        .addComponent(cxQtdePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addComponent(btCadastrar)
                    .addContainerGap(67, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        insCarro();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaActionPerformed
        consCarro();
    }//GEN-LAST:event_btConsultaActionPerformed

    private void btAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlteraActionPerformed
        altCarro();
    }//GEN-LAST:event_btAlteraActionPerformed

    private void btDeletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletaActionPerformed
        delCarroPlaca();
    }//GEN-LAST:event_btDeletaActionPerformed

    private void btPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPessoaActionPerformed
        chamaTabela();
    }//GEN-LAST:event_btPessoaActionPerformed

    private void btVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVeicActionPerformed
        chamaTabelaVeic();
    }//GEN-LAST:event_btVeicActionPerformed
    public void chamaTabelaVeic(){
        TabelaGeralVeiculos.getCadVeicUnic().setVisible(true);
    }
    public void chamaTabela(){
        TabelaGeral.getCadTabelaUnic().setVisible(true);
    }
    private boolean camposVazios() {
        return cxTarifa.getText().isEmpty()
                || cxDistancia.getText().isEmpty()
                || cxPlaca.getText().isEmpty()
                || cxCor.getText().isEmpty()
                || cxTipoCorrida.getText().isEmpty();
                
    }

    public void insCarro(){
        Carro ca = new Carro();
        
        if (camposVazios()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Preencha todos os campos para cadastrar o motorista.",
                    "Campos Vazios",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
    try {
        ca.setPlaca(cxPlaca.getText());
    } catch (PlacaException ex) {
        ex.impErroPlaca();
	ca =(Carro) ex.corPlaca(ca);
        Logger.getLogger(CadastroCarro.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        ca.setCor(cxCor.getText());
        
        ca.setCorrida(cxTipoCorrida.getText());
            boolean distanciaValida = false;
        while (!distanciaValida) {
            try {
                     ca.setDistancia(Double.parseDouble(cxDistancia.getText()));
                    distanciaValida = true; 
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(
                    null,
                    "A Distância deve ser um numero.",
                    "Erro de Formato",
                    JOptionPane.ERROR_MESSAGE
                );



                cxDistancia.setText(JOptionPane.showInputDialog(null, "INFORME A DISTÂNCIA NOVAMENTE:"));
            }
        }
    //-----------------------------------------------------------------
       
    //--------------------------------------------------------------
    boolean tarifaValida = false;
        while (!tarifaValida) {
            try {
                    ca.setTarifa(Float.parseFloat(cxTarifa.getText()));
                    tarifaValida = true; // Define como verdadeiro se a conversão for bem-sucedida
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(
                    null,
                    "A tarifa deve ser um numero.",
                    "Erro de Formato",
                    JOptionPane.ERROR_MESSAGE
                );



                cxTarifa.setText(JOptionPane.showInputDialog(null, "INFORME A TARIFA NOVAMENTE:"));
            }
        }
    //--------------------------------------------------------------
        
        ca.setPassageiro(Integer.parseInt(cxQtdePassageiro.getText()));
        //arrumar
        ca = GerCarro.geraGerCarro().insCarro(ca);
        
        if(ca != null){
           JOptionPane.showMessageDialog(
                   null,
                   "CARRO CADASTRADO",
                   "Confirmar Cadastro",
                   JOptionPane.INFORMATION_MESSAGE
           
           );
        }
        else{
            JOptionPane.showMessageDialog(
                   null,
                   "ERRO AO CADASTRAR CARRO",
                   "ERRO",
                   JOptionPane.ERROR_MESSAGE
            );
        }
        limpar();
    }
    //arrumar
    public void consCarro() {
    Carro ca = new Carro();

    if (cxPlaca.getText().isEmpty()) {
        JOptionPane.showMessageDialog(
            null,
            "Digite a placa para consultar o carro.",
            "Campo Vazio",
            JOptionPane.WARNING_MESSAGE
        );
        return; // Não prosseguir se o campo de placa estiver vazio
    }
    
    try {
        ca.setPlaca(cxPlaca.getText());
    } catch (PlacaException ex) {
        ex.impErroPlaca();
	ca =(Carro) ex.corPlaca(ca);
        Logger.getLogger(CadastroCarro.class.getName()).log(Level.SEVERE, null, ex);
    }

    ca= GerCarro.geraGerCarro().consCarroPlaca(ca); // Realiza a consulta do carro pela placa
    
    if (ca != null) {
        // Exibir informações do carro encontrado nos campos correspondentes
        cxPlaca.setText(ca.getPlaca());
        cxCor.setText(ca.getCor());
        cxQtdePassageiro.setText(String.valueOf(ca.getQtdePassageiro()));
        cxTarifa.setText(String.valueOf(ca.getTarifa()));
        cxTipoCorrida.setText(ca.getCorrida());
        cxDistancia.setText(String.valueOf(ca.getTarifa()));

        // Exibir mensagem indicando que o carro foi encontrado
        JOptionPane.showMessageDialog(
            null,
            "CARRO ENCONTRADO",
            "CONSULTA DE CARRO",
            JOptionPane.INFORMATION_MESSAGE
        );
    } else {
        // Limpar campos se o carro não for encontrado e exibir mensagem de erro
        limpar();
        JOptionPane.showMessageDialog(
            null,
            "PLACA NÃO ENCONTRADA",
            "CARRO NÃO CADASTRADO",
            JOptionPane.ERROR_MESSAGE
        );
    }
}

    public void altCarro() {
    Carro ca = new Carro();
    
    if (camposVazios()) {
        JOptionPane.showMessageDialog(
            null,
            "Preencha todos os campos para alterar os dados do carro.",
            "Campos Vazios",
            JOptionPane.WARNING_MESSAGE
        );
        return; // Não prosseguir se houver campos vazios
    }

    try {
        ca.setPlaca(cxPlaca.getText());
    } catch (PlacaException ex) {
        ex.impErroPlaca();
	ca =(Carro) ex.corPlaca(ca);
        Logger.getLogger(CadastroCarro.class.getName()).log(Level.SEVERE, null, ex);
    }

    ca = GerCarro.geraGerCarro().atualizaCarro(ca); // Atualiza o carro com base na placa fornecida
    
    if (ca != null) {
        // Preenche os campos com as informações atualizadas do carro
        cxPlaca.setText(ca.getPlaca());
  
        cxCor.setText(ca.getCor());
        // ... preencher outros campos conforme necessário

        JOptionPane.showMessageDialog(
            null,
            "DADOS DO CARRO ALTERADOS",
            "ALTERAÇÃO DE CADASTRO",
            JOptionPane.INFORMATION_MESSAGE
        );
    } else {
        limpar(); // Limpa os campos se o carro não for encontrado
        JOptionPane.showMessageDialog(
            null,
            "PLACA NÃO ENCONTRADA",
            "CARRO NÃO ENCONTRADO",
            JOptionPane.ERROR_MESSAGE
        );
    }
}

    public void delCarroPlaca() {
    Carro ca = new Carro();

    if (cxPlaca.getText().isEmpty()) {
        JOptionPane.showMessageDialog(
            null,
            "Digite a placa para excluir o carro.",
            "Campo Vazio",
            JOptionPane.WARNING_MESSAGE
        );
        return; // Não prosseguir se o campo de placa estiver vazio
    }

    try {
        ca.setPlaca(cxPlaca.getText());
    } catch (PlacaException ex) {
        ex.impErroPlaca();
	ca =(Carro) ex.corPlaca(ca);
        Logger.getLogger(CadastroCarro.class.getName()).log(Level.SEVERE, null, ex);
    }

    // Comunica com GerCarro para excluir o carro pela placa
    ca = GerCarro.geraGerCarro().delCarroPlaca(ca);

    if (ca == null) {
        JOptionPane.showMessageDialog(
            null,
            "CARRO EXCLUÍDO",
            "EXCLUIR CARRO",
            JOptionPane.INFORMATION_MESSAGE
        );
    } else {
        JOptionPane.showMessageDialog(
            null,
            "PLACA NÃO ENCONTRADA",
            "CARRO NÃO ENCONTRADO",
            JOptionPane.ERROR_MESSAGE
        );
    }
    limpar(); // Limpa os campos após a exclusão
}

   
   
    public void limpar(){
        cxCor.setText("");
        cxPlaca.setText("");
        cxTarifa.setText("");
        cxTipoCorrida.setText("");
        cxQtdePassageiro.setText("");
        cxDistancia.setText("");
        
        cxPlaca.requestFocus();
        
    }
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
                //janela de confirmação
        );
        
        if(resp == 0){
            dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltera;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConsulta;
    private javax.swing.JButton btDeleta;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPessoa;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVeic;
    private javax.swing.JTextField cxCor;
    private javax.swing.JTextField cxDistancia;
    private javax.swing.JTextField cxPlaca;
    private javax.swing.JTextField cxQtdePassageiro;
    private javax.swing.JTextField cxTarifa;
    private javax.swing.JTextField cxTipoCorrida;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lCpfMot;
    private javax.swing.JLabel lIdadeMot;
    private javax.swing.JLabel lNomeMot;
    private javax.swing.JLabel lPaisMot;
    private javax.swing.JLabel lQtdeViagemot;
    private javax.swing.JLabel lRuaMot;
    // End of variables declaration//GEN-END:variables
}
