//Nome: Murillo Tadeu Amadeu -  RA: 02564246
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetofinal;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author muril
 */
public class CadastroCliente extends javax.swing.JFrame {
    //metodo singleton
    static CadastroCliente cadClienteUnic;
    public static CadastroCliente getCadClienteUnic(){
        if(cadClienteUnic == null){
            cadClienteUnic = new CadastroCliente();
        }
        return cadClienteUnic;
        
    }
    /**
     * Creates new form CadastroCliente
     */
    private CadastroCliente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lPais = new javax.swing.JLabel();
        cxNumero = new javax.swing.JTextField();
        lRua = new javax.swing.JLabel();
        cxPais = new javax.swing.JTextField();
        lNumero = new javax.swing.JLabel();
        cxRua = new javax.swing.JTextField();
        cxIdade = new javax.swing.JTextField();
        lNome = new javax.swing.JLabel();
        cxCpf = new javax.swing.JTextField();
        lIdade = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        lCpf = new javax.swing.JLabel();
        lTituloCliente = new javax.swing.JLabel();
        lValorGasto = new javax.swing.JLabel();
        cxValorGasto = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btCadastro = new javax.swing.JButton();
        btPesquisa = new javax.swing.JButton();
        btAltera = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        lImpPro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbSeleciona = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Cliente");

        lPais.setText("Pais:");

        lRua.setText("Rua:");

        lNumero.setText("Numero:");

        lNome.setText("  Nome:");

        lIdade.setText("  Idade:");

        lCpf.setText("  Cpf:");

        lTituloCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lTituloCliente.setText("Informações do Cliente:");

        lValorGasto.setText("  Valor Gasto:");

        btSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btLimpar.setText("Limpar Formulário");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCadastro.setText("Cadastrar...");
        btCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroActionPerformed(evt);
            }
        });

        btPesquisa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btPesquisa.setText("Pesquisar");
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });

        btAltera.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAltera.setText("Alterar Cadastro");
        btAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlteraActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btExcluir.setText("Excluir Cadastro");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        lImpPro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Selecione o veiculo:");

        cbSeleciona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "Moto", "Ônibus", "Carro" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Para Pesquisar digitar apenas cpf válido que ja tenha cadastro");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Vizualizar Pessoas Cadastradas...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lRua, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxRua, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(408, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(256, 256, 256))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lImpPro, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lPais, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lTituloCliente))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lIdade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lValorGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cxValorGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(btPesquisa)
                                .addGap(18, 18, 18)
                                .addComponent(btAltera)
                                .addGap(18, 18, 18)
                                .addComponent(btExcluir))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(138, 138, 138)))
                .addContainerGap(234, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btLimpar)
                        .addGap(36, 36, 36)
                        .addComponent(btSair)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSeleciona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTituloCliente)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNome)
                            .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lCpf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lIdade)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lRua)
                            .addComponent(cxRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lPais))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNumero)
                            .addComponent(cxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lValorGasto)
                    .addComponent(cxValorGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lImpPro)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSeleciona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastro)
                    .addComponent(btPesquisa)
                    .addComponent(btAltera)
                    .addComponent(btExcluir))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btLimpar)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroActionPerformed
        passaPag();
        
    }//GEN-LAST:event_btCadastroActionPerformed

    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed
        consCliente();
    }//GEN-LAST:event_btPesquisaActionPerformed

    private void btAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlteraActionPerformed
        altCliente();
    }//GEN-LAST:event_btAlteraActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        delClienteCpf();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        chamaTabela();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void chamaTabela(){
        TabelaGeral.getCadTabelaUnic().setVisible(true);
    }
    public void passaPag(){
        String veiculo = cbSeleciona.getSelectedItem().toString();
        if(camposVazios() == true){
                insCliente();
        }else if(veiculo.equals("Escolha")){
                JOptionPane.showMessageDialog(
                    null,
                    "SELECIONE UMA OPÇÃO DE VEICULO.",
                    "Campos Vazios",
                    JOptionPane.WARNING_MESSAGE
                );
            return;
        }else{
        insCliente();
        selecionaVeic();
        }
    }
    public void selecionaVeic(){
        String veiculo = cbSeleciona.getSelectedItem().toString();
            if(veiculo.equals("Carro")){
                CadastroCarro();
            }else if(veiculo.equals("Moto")){
                CadastroMoto();
            }else if(veiculo.equals("Ônibus")){
                CadastroOnibus();
            }
    }
     public void CadastroOnibus(){
        CadastroOnibus.getCadOnibusUnic().setVisible(true);
    }
    public void CadastroCarro(){
        CadastroCarro.getCadCarroUnic().setVisible(true);
    }
    public void CadastroMoto(){
        CadastroMoto.getCadPMotoUnic().setVisible(true); 
    }
    private boolean camposVazios() {
        return cxCpf.getText().isEmpty()
                || cxNome.getText().isEmpty()
                || cxRua.getText().isEmpty()
                || cxPais.getText().isEmpty()
                || cxNumero.getText().isEmpty()
                || cxIdade.getText().isEmpty()
                || cxValorGasto.getText().isEmpty();
    }
    public void insCliente(){
        Cliente cl = new Cliente();
        if (camposVazios()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Preencha todos os campos para cadastrar o Cliente.",
                    "Campos Vazios",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        boolean cpfValido = false;

    while (!cpfValido) {
        try {
            cl.setCpf(Integer.parseInt(cxCpf.getText()));
            cpfValido = true; // Define como verdadeiro se a conversão for bem-sucedida
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(
                null,
                "O CPF deve ser um número válido.",
                "Erro de Formato",
                JOptionPane.ERROR_MESSAGE
            );
        

        
            cxCpf.setText(JOptionPane.showInputDialog(null, "INFORME O CPF NOVAMENTE:"));
        }
    }

        try {
            cl.setNome(cxNome.getText());
        } catch (NomeException ex) {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        cl.getEnder().setRua(cxRua.getText());
        cl.getEnder().setPais(cxPais.getText());
        cl.getEnder().setNumero(Integer.parseInt(cxNumero.getText()));
        cl.setValorGasto(Double.valueOf(cxValorGasto.getText()));
       try {
        cl.setIdade(Integer.parseInt(cxIdade.getText()));
        } catch (IdadeException ex) {
        IdadeException idadeExcecao = new IdadeException();
        Pessoa pessoaAtualizada = idadeExcecao.corIdade(cl);
        cl = (Cliente) pessoaAtualizada;
    } catch (NumberFormatException ex) {
        IdadeException idadeExcecao = new IdadeException();
        Pessoa pessoaAtualizada = idadeExcecao.corIdade(cl);
        cl = (Cliente) pessoaAtualizada;
    }

        
        cl = GerCliente.geraGerCliente().insCliente(cl);
        
        if(cl != null){
           JOptionPane.showMessageDialog(
                   null,
                   "Cliente Cadastrado",
                   "Confirma Cadastro",
                   JOptionPane.INFORMATION_MESSAGE
           
           );
        }
        else{
            JOptionPane.showMessageDialog(
                   null,
                   "ERRO AO CADASTRAR CLIENTE",
                   "ERRO",
                   JOptionPane.ERROR_MESSAGE
            );
        }
        limpar();
    }
    public void consCliente(){
        Cliente cl = new Cliente();
        if (cxCpf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Digite o CPF para consultar o motorista.",
                    "Campo Vazio",
                    JOptionPane.WARNING_MESSAGE
            );
            return; 
        }
        cl.setCpf(Integer.parseInt(cxCpf.getText()));
        
        //comunica com GerPes
        cl = GerCliente.geraGerCliente().consClienteCpf(cl);
        
        if(cl != null){
            cxCpf.setText(Integer.toString(cl.getCpf()));
            cxNome.setText(cl.getNome());
            cxRua.setText(cl.getEnder().getRua());
            cxPais.setText(cl.getEnder().getPais());
            cxNumero.setText(String.valueOf(cl.getEnder().getNumero()));
            cxIdade.setText(String.valueOf(cl.getIdade()));
            lImpPro.setText(String.valueOf(cl.impPro()));
           JOptionPane.showMessageDialog(
                   null,
                   "CLIENTE ENCONTRADO",
                   "CONSULTA DE CLIENTE",
                   JOptionPane.INFORMATION_MESSAGE
           
           );
        }
        else{
            limpar();
            JOptionPane.showMessageDialog(
                   null,
                   "CPF NÃO ENCONTRADO",
                   "CLIENTE NÃO CADASTRADO",
                   JOptionPane.ERROR_MESSAGE
            );
        }
        
    }
    public void altCliente(){
        Cliente cl = new Cliente();
        if (camposVazios()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Preencha todos os campos para alterar os dados do motorista.",
                    "Campos Vazios",
                    JOptionPane.WARNING_MESSAGE
            );
            return; 
        }
        cl.setCpf(Integer.parseInt(cxCpf.getText()));
        
        
        cl = GerCliente.geraGerCliente().atualizaClienteCpf(cl);
        
        if(cl != null){
            cxCpf.setText(Integer.toString(cl.getCpf()));
            cxNome.setText(cl.getNome());
            cxRua.setText(cl.getEnder().getRua());
            cxPais.setText(cl.getEnder().getPais());
            cxNumero.setText(String.valueOf(cl.getEnder().getNumero()));
            lImpPro.setText(String.valueOf(cl.impPro()));
            cxIdade.setText(String.valueOf(cl.getIdade()));
           JOptionPane.showMessageDialog(
                   null,
                   "DADOS DO CLIENTE ALTERADO",
                   "ALETRAÇÃO DE CADASTRO",
                   JOptionPane.INFORMATION_MESSAGE
           
           );
        }
        else{
            limpar();
            JOptionPane.showMessageDialog(
                   null,
                   "CPF NÃO ENCONTRADO",
                   "CLIENTE NÃO ENCONTRADO",
                   JOptionPane.ERROR_MESSAGE
            );
        }
        //limpar();
    }
    public void delClienteCpf(){
        Cliente cl = new Cliente();
         if (cxCpf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Digite o CPF para excluir o motorista.",
                    "Campo Vazio",
                    JOptionPane.WARNING_MESSAGE
            );
            return; 
        }
        cl.setCpf(Integer.parseInt(cxCpf.getText()));
        
        //comunica com GerPes
        cl = GerCliente.geraGerCliente().delClienteCpf(cl);
        
        if(cl == null){
            
           JOptionPane.showMessageDialog(
                   null,
                   "CLIENTE EXCLUIDO",
                   "EXCLUIR CLIENTE",
                   JOptionPane.INFORMATION_MESSAGE
           
           );
        }
        else{
 
            JOptionPane.showMessageDialog(
                   null,
                   "CPF NÃO ENCONTRADO",
                   "CLIENTE NÃO ENCONTRADO",
                   JOptionPane.ERROR_MESSAGE
            );
        }
        limpar();
    }
    public void limpar(){
        cxCpf.setText("");
        cxNome.setText("");
        cxIdade.setText("");
        cxNumero.setText("");
        cxRua.setText("");
        cxValorGasto.setText("");
        cxPais.setText("");
        
        cxNome.requestFocus();
        
    }
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
                //janela de confirmação
        );
        
        if(resp == 0){
            dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltera;
    private javax.swing.JButton btCadastro;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisa;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> cbSeleciona;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxIdade;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxNumero;
    private javax.swing.JTextField cxPais;
    private javax.swing.JTextField cxRua;
    private javax.swing.JTextField cxValorGasto;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lCpf;
    private javax.swing.JLabel lIdade;
    private javax.swing.JLabel lImpPro;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lPais;
    private javax.swing.JLabel lRua;
    private javax.swing.JLabel lTituloCliente;
    private javax.swing.JLabel lValorGasto;
    // End of variables declaration//GEN-END:variables
}
