//Nome: Murillo Tadeu Amadeu -  RA: 02564246
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetofinal;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author muril
 */
public class CadastroMoto extends javax.swing.JFrame {
    //metodo singleton
    static CadastroMoto cadMotoUnic;    
    public static CadastroMoto getCadPMotoUnic(){
        if(cadMotoUnic == null){
            cadMotoUnic = new CadastroMoto();
        }
        return cadMotoUnic;
        
    }
    /**
     * Creates new form CadastroMoto
     */
    private CadastroMoto() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cxCor = new javax.swing.JTextField();
        cxTarifa = new javax.swing.JTextField();
        cxQtdePassageiro = new javax.swing.JTextField();
        cxTipoCorrida = new javax.swing.JTextField();
        cxDistancia = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        lNomeMot = new javax.swing.JLabel();
        lCpfMot = new javax.swing.JLabel();
        lIdadeMot = new javax.swing.JLabel();
        lQtdeViagemot = new javax.swing.JLabel();
        lRuaMot = new javax.swing.JLabel();
        lPaisMot = new javax.swing.JLabel();
        cxPlaca = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btPessoa = new javax.swing.JButton();
        btVeic = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Moto");

        btSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btLimpar.setText("Limpar Formulário");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        lNomeMot.setText("Placa:");

        lCpfMot.setText("Cor:");

        lIdadeMot.setText("Tarifa unitária:");

        lQtdeViagemot.setText("Quantidade de Passageiros:");

        lRuaMot.setText("Tipo de corrida:");

        lPaisMot.setText("Distância:");

        btCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        jButton3.setText("Deletar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btPessoa.setText("Tabela Cadastro Pessoas...");
        btPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPessoaActionPerformed(evt);
            }
        });

        btVeic.setText("Tabela Cadastro veiculos...");
        btVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVeicActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Para Pesquisar digite uma placa válida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btCadastrar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lQtdeViagemot, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cxQtdePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(btConsultar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btAlterar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btPessoa)
                                        .addGap(18, 18, 18)
                                        .addComponent(btVeic))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lNomeMot, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lCpfMot, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cxCor)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lIdadeMot)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cxTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lRuaMot)
                                    .addComponent(lPaisMot))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cxTipoCorrida, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(cxDistancia))))
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(417, 417, 417)
                    .addComponent(btLimpar)
                    .addGap(52, 52, 52)
                    .addComponent(btSair)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomeMot)
                    .addComponent(cxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRuaMot)
                    .addComponent(cxTipoCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCpfMot)
                    .addComponent(cxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPaisMot)
                    .addComponent(cxDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lIdadeMot))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lQtdeViagemot)
                    .addComponent(cxQtdePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar)
                    .addComponent(btAlterar)
                    .addComponent(jButton3))
                .addGap(25, 25, 25)
                .addComponent(btCadastrar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPessoa)
                    .addComponent(btVeic))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(327, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSair)
                        .addComponent(btLimpar))
                    .addGap(15, 15, 15)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        insMoto();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consMoto();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        altMoto();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        delMotoPlaca();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPessoaActionPerformed
        chamaTabela();
    }//GEN-LAST:event_btPessoaActionPerformed

    private void btVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVeicActionPerformed
        chamaTabelaVeic();
    }//GEN-LAST:event_btVeicActionPerformed
    
    public void chamaTabelaVeic(){
        TabelaGeralVeiculos.getCadVeicUnic().setVisible(true);
    }
    public void chamaTabela(){
        TabelaGeral.getCadTabelaUnic().setVisible(true);
    }
    private boolean camposVazios() {
        return cxTarifa.getText().isEmpty()
                || cxDistancia.getText().isEmpty()
                || cxPlaca.getText().isEmpty()
                || cxCor.getText().isEmpty()
                || cxTipoCorrida.getText().isEmpty();
                
    }

    public void insMoto(){
        Moto mo = new Moto();
        
        if (camposVazios()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Preencha todos os campos para cadastrar o motorista.",
                    "Campos Vazios",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
    try {
        mo.setPlaca(cxPlaca.getText());
    } catch (PlacaException ex) {
        ex.impErroPlaca();
	mo =(Moto) ex.corPlaca(mo);
        Logger.getLogger(CadastroCarro.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        mo.setCor(cxCor.getText());
        
        mo.setTipoCorrida(cxTipoCorrida.getText());
    //-----------------------------------------------------------------
    boolean distanciaValida = false;
        while (!distanciaValida) {
            try {
                     mo.setDistancia(Double.parseDouble(cxDistancia.getText()));
                    distanciaValida = true; 
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(
                    null,
                    "A Distância deve ser um numero.",
                    "Erro de Formato",
                    JOptionPane.ERROR_MESSAGE
                );



                cxDistancia.setText(JOptionPane.showInputDialog(null, "INFORME A DISTÂNCIA NOVAMENTE:"));
            }
        }
    //-----------------------------------------------------------------
       
    //--------------------------------------------------------------
    boolean tarifaValida = false;
        while (!tarifaValida) {
            try {
                    mo.setTarifa(Float.parseFloat(cxTarifa.getText()));
                    tarifaValida = true; // Define como verdadeiro se a conversão for bem-sucedida
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(
                    null,
                    "A tarifa deve ser um numero.",
                    "Erro de Formato",
                    JOptionPane.ERROR_MESSAGE
                );



                cxTarifa.setText(JOptionPane.showInputDialog(null, "INFORME A TARIFA NOVAMENTE:"));
            }
        }
    //--------------------------------------------------------------
        
        mo.setPassageiro(Integer.parseInt(cxQtdePassageiro.getText()));
        //arrumar
        mo = GerMoto.geraGerMoto().insMoto(mo);
        
        if(mo != null){
           JOptionPane.showMessageDialog(
                   null,
                   "MOTO CADASTRADA",
                   "Confirmar Cadastro",
                   JOptionPane.INFORMATION_MESSAGE
           
           );
        }
        else{
            JOptionPane.showMessageDialog(
                   null,
                   "ERRO AO CADASTRAR CARRO",
                   "ERRO",
                   JOptionPane.ERROR_MESSAGE
            );
        }
        limpar();
    }
    //arrumar
    public void consMoto() {
    Moto mo = new Moto();

    if (cxPlaca.getText().isEmpty()) {
        JOptionPane.showMessageDialog(
            null,
            "Digite a placa para consultar o carro.",
            "Campo Vazio",
            JOptionPane.WARNING_MESSAGE
        );
        return; // Não prosseguir se o campo de placa estiver vazio
    }
    
        try {
        mo.setPlaca(cxPlaca.getText());
    } catch (PlacaException ex) {
        ex.impErroPlaca();
	mo =(Moto) ex.corPlaca(mo);
        Logger.getLogger(CadastroCarro.class.getName()).log(Level.SEVERE, null, ex);
    }

    mo= GerMoto.geraGerMoto().consMotoPlaca(mo); // Realiza a consulta do carro pela placa
    
    if (mo != null) {
        // Exibir informações do carro encontrado nos campos correspondentes
        cxPlaca.setText(mo.getPlaca());
        cxCor.setText(mo.getCor());
        cxQtdePassageiro.setText(String.valueOf(mo.getQtdePassageiro()));
        cxTarifa.setText(String.valueOf(mo.getTarifa()));
        cxTipoCorrida.setText(mo.getCorrida());
        cxDistancia.setText(String.valueOf(mo.getDistancia()));

        // Exibir mensagem indicando que o carro foi encontrado
        JOptionPane.showMessageDialog(
            null,
            "CARRO ENCONTRADO",
            "CONSULTA DE MOTO",
            JOptionPane.INFORMATION_MESSAGE
        );
    } else {
        // Limpar campos se o carro não for encontrado e exibir mensagem de erro
        limpar();
        JOptionPane.showMessageDialog(
            null,
            "PLACA NÃO ENCONTRADA",
            "MOTO NÃO CADASTRADA",
            JOptionPane.ERROR_MESSAGE
        );
    }
}

    public void altMoto() {
    Moto mo = new Moto();
    
    if (camposVazios()) {
        JOptionPane.showMessageDialog(
            null,
            "Preencha todos os campos para alterar os dados da moto.",
            "Campos Vazios",
            JOptionPane.WARNING_MESSAGE
        );
        return; // Não prosseguir se houver campos vazios
    }

         try {
        mo.setPlaca(cxPlaca.getText());
    } catch (PlacaException ex) {
        ex.impErroPlaca();
	mo =(Moto) ex.corPlaca(mo);
        Logger.getLogger(CadastroCarro.class.getName()).log(Level.SEVERE, null, ex);
    }

    mo = GerMoto.geraGerMoto().atualizaMoto(mo); // Atualiza o carro com base na placa fornecida
    
    if (mo != null) {
        // Preenche os campos com as informações atualizadas do carro
        cxPlaca.setText(mo.getPlaca());
  
        cxCor.setText(mo.getCor());
        // ... preencher outros campos conforme necessário

        JOptionPane.showMessageDialog(
            null,
            "DADOS DA MOTO ALTERADOS",
            "ALTERAÇÃO DE CADASTRO",
            JOptionPane.INFORMATION_MESSAGE
        );
    } else {
        limpar(); // Limpa os campos se o carro não for encontrado
        JOptionPane.showMessageDialog(
            null,
            "PLACA NÃO ENCONTRADA",
            "MOTO NÃO ENCONTRADA",
            JOptionPane.ERROR_MESSAGE
        );
    }
}

    public void delMotoPlaca() {
    Moto mo = new Moto();

    if (cxPlaca.getText().isEmpty()) {
        JOptionPane.showMessageDialog(
            null,
            "Digite a placa para excluir a moto.",
            "Campo Vazio",
            JOptionPane.WARNING_MESSAGE
        );
        return; // Não prosseguir se o campo de placa estiver vazio
    }

         try {
        mo.setPlaca(cxPlaca.getText());
    } catch (PlacaException ex) {
        ex.impErroPlaca();
	mo =(Moto) ex.corPlaca(mo);
        Logger.getLogger(CadastroCarro.class.getName()).log(Level.SEVERE, null, ex);
    }

    
    mo = GerMoto.geraGerMoto().delMotoPlaca(mo);

    if (mo == null) {
        JOptionPane.showMessageDialog(
            null,
            "MOTO EXCLUIDA",
            "EXCLUIR MOTO",
            JOptionPane.INFORMATION_MESSAGE
        );
    } else {
        JOptionPane.showMessageDialog(
            null,
            "PLACA NÃO ENCONTRADA",
            "MOTO NÃO ENCONTRADA",
            JOptionPane.ERROR_MESSAGE
        );
    }
    limpar(); // Limpa os campos após a exclusão
}
    public void limpar(){
        cxCor.setText("");
        cxPlaca.setText("");
        cxTarifa.setText("");
        cxTipoCorrida.setText("");
        cxQtdePassageiro.setText("");
        cxDistancia.setText("");
        
        cxPlaca.requestFocus();
        
    }
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
                //janela de confirmação
        );
        
        if(resp == 0){
            dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPessoa;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVeic;
    private javax.swing.JTextField cxCor;
    private javax.swing.JTextField cxDistancia;
    private javax.swing.JTextField cxPlaca;
    private javax.swing.JTextField cxQtdePassageiro;
    private javax.swing.JTextField cxTarifa;
    private javax.swing.JTextField cxTipoCorrida;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lCpfMot;
    private javax.swing.JLabel lIdadeMot;
    private javax.swing.JLabel lNomeMot;
    private javax.swing.JLabel lPaisMot;
    private javax.swing.JLabel lQtdeViagemot;
    private javax.swing.JLabel lRuaMot;
    // End of variables declaration//GEN-END:variables
}
