//Nome: Murillo Tadeu Amadeu -  RA: 02564246
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetofinal;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author muril
 */
public class TabelaGeral extends javax.swing.JFrame {
    //metodo singleton
    static TabelaGeral cadTabelaUnic;
 
    public static TabelaGeral getCadTabelaUnic(){
        if(cadTabelaUnic == null){
            cadTabelaUnic = new TabelaGeral();
        }
        return cadTabelaUnic;
        
    }
    /**
     * Creates new form TabelaGeral
     */
    private TabelaGeral() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabCliente = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabMotorista = new javax.swing.JTable();
        lMoto = new javax.swing.JLabel();
        lCliente = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pessoas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NOME", "RUA", "PAIS", "NUMERO", "IDADE", "CLASSIFICAÇÃO"
            }
        ));
        tabCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabCliente);

        tabMotorista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NOME", "RUA", "PAIS", "NUMERO", "IDADE", "CLASSIFICAÇÃO"
            }
        ));
        tabMotorista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMotoristaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabMotorista);

        lMoto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lMoto.setText("MOTORISTAS CADASTRADOS:");

        lCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lCliente.setText("CLIENTES CADASTRADOS:");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Vizualizar Veiculos Cadastrados...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(74, 74, 74)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)))
                .addGap(4, 4, 4)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(73, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lMoto)
                .addGap(182, 182, 182)
                .addComponent(lCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(299, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sair();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarTab();
    }//GEN-LAST:event_formWindowActivated

    private void tabClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabClienteMouseClicked
        selecionarItem();
    }//GEN-LAST:event_tabClienteMouseClicked

    private void tabMotoristaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMotoristaMouseClicked
        selecionarItemMotorista();
    }//GEN-LAST:event_tabMotoristaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        chamaTabelaVeic();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void chamaTabelaVeic(){
        TabelaGeralVeiculos.getCadVeicUnic().setVisible(true);
    }
    public void listarTab(){
        DefaultTableModel modelo = (DefaultTableModel) tabCliente.getModel();
        DefaultTableModel modeloMotorista = (DefaultTableModel) tabMotorista.getModel();
        int poslin = 0;
        int poslimMotorista =0;
        
        
        modelo.setRowCount(poslin);
        modeloMotorista.setRowCount(poslimMotorista);
        
        
        for (Motorista mo : GerMotorista.geraGerMotorista().getBdMoto()){
            modeloMotorista.insertRow(poslimMotorista, new Object[]
                    {mo.getCpf(),mo.getNome(),
                     mo.getEnder().getRua(),
                     mo.getEnder().getPais(),
                     String.valueOf(mo.getEnder().getNumero()),
                     String.valueOf(mo.getIdade()),
                     String.valueOf(mo.impPro())
            });
            poslimMotorista++;
        }
        
        for (Cliente cl : GerCliente.geraGerCliente().getBdCl()){
            modelo.insertRow(poslin, new Object[]
                    {cl.getCpf(),cl.getNome(),
                     cl.getEnder().getRua(),
                     cl.getEnder().getPais(),
                     String.valueOf(cl.getEnder().getNumero()),
                     String.valueOf(cl.getIdade()),
                     String.valueOf(cl.impPro())
            });
            poslin++;
        }
    }
    
    public void selecionarItemMotorista(){
        String linTab = "";
        
        int poslin = tabMotorista.getSelectedRow();
        
        for(int col = 0; col <tabMotorista.getColumnCount(); col++){
            linTab += "/ "+ tabMotorista.getModel().getValueAt(poslin, col).toString();
            
        }
        JOptionPane.showMessageDialog(
                null,
                "VALORES SELECIONADOS SÃO: "+linTab+" ",
                "CAPTURA TABELA",
                1
        );
    }
    public void selecionarItem(){
        String linTab = "";
        
        int poslin = tabCliente.getSelectedRow();
        
        for(int col = 0; col <tabCliente.getColumnCount(); col++){
            linTab +="/ "+ tabCliente.getModel().getValueAt(poslin, col).toString();
        }
        JOptionPane.showMessageDialog(
                null,
                "VALORES SELECIONADOS SÃO: "+linTab+" ",
                "CAPTURA TABELA",
                1
        );
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida",
                JOptionPane.YES_NO_OPTION
                //janela de confirmação
        );
        
        if(resp == 0){
            dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaGeral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lCliente;
    private javax.swing.JLabel lMoto;
    private javax.swing.JTable tabCliente;
    private javax.swing.JTable tabMotorista;
    // End of variables declaration//GEN-END:variables
}
